version: 2
common_setup_command: &common_setup_command
  command: |
    apk add git
    apk add bash
    git config --global push.default simple
    git config --global user.email matsunoappy@gmail.com
    git config --global user.name himanoa
jobs:
  release_firestore_testing:
    docker:
      - image: "docker:18.06.3-ce"
    steps:
      - checkout
      - run:
          <<: *common_setup_command
      - setup_remote_docker
      - run:
          name: Run
          command: |
            if bash bin/Changed "firestore-testing"; then
              cd firestore-testing
              docker build -t himanoa/firestore-testing .
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push himanoa/firestore-testing
              git commit --allow-empty -m "[ci-skip] Release firestore-testing"
            fi
workflows:
  version: 2
  test:
    jobs:
      - release_firestore_testing
